In [26]:
import pgeocode
import pandas as pd
import re

In [4]:
nomi = pgeocode.Nominatim('es')

In [6]:
data = pd.read_csv('variables_codigo_postal.csv')

In [7]:
data.shape

(6375, 54)

In [8]:
data.columns

Index(['CODIGO_POSTAL_NUMBER', 'mediaEdad', 'medianaEdad',
       'nivel_socio_economico', 'GMTotal', 'GMVivienda', 'GMMobiliario',
       'GMEnsenanza', 'GMElectricidad', 'GMGasNatural', 'GMSalud', 'GMSeguros',
       'TIPOLOGIA_LITERAL', 'Ingresos_brutos_hogar',
       'media_viviend_x_edificio', 'Sup_media_vivienda', 'CODIGO_POSTAL',
       'p_suelo_uso_residencial', 'p_suelo_uso_industrial',
       'p_suelo_uso_oficinas', 'p_suelo_uso_comercial',
       'p_suelo_ocio_hosteleria', 'p_suelo_uso_deportivo', 'p_otros_usos',
       'p_mujeres', 'p_extranjeros', 'p_solteros', 'p_casados', 'p_viudos',
       'p_separados', 'p_divorciados', 'p_analfabetos', 'p_sinestudios',
       'p_estudios_1er_grado', 'p_estudios_2o_grado', 'p_estudios_3er_grado',
       'p_estudiantes', 'p_ocupados', 'p_viv_1_persona', 'p_viv_2_personas',
       'p_viv_3_personas', 'p_viv_4_personas', 'p_viv_mas4_personas',
       'p_viviendas_c_delinc', 'p_viviendas_ruina', 'p_viviendas_mal_estado',
       'p_viviend_estado_defic', 'p_viviendas_buen_estado', 'p_paro_2015',
       'p_turismos', 'p_vehiculos_comerciales', 'p_monovolumenes',
       'p_motocicletas', 'p_todoterrenos'],
      dtype='object')

In [18]:
data.head()

,CODIGO_POSTAL_NUMBER,mediaEdad,medianaEdad,nivel_socio_economico,GMTotal,GMVivienda,GMMobiliario,GMEnsenanza,GMElectricidad,GMGasNatural,...,p_viviendas_ruina,p_viviendas_mal_estado,p_viviend_estado_defic,p_viviendas_buen_estado,p_paro_2015,p_turismos,p_vehiculos_comerciales,p_monovolumenes,p_motocicletas,p_todoterrenos
0,8004.0,42.58,Población de 35 a 39 años,3.98,26365.40,11457.62,1041.14,461.21,586.44,278.10,...,1.500000,5.636364,24.045455,68.818182,7.129569,2.042449,0.742163,0.894197,1.062234,1.080238
1,43203.0,41.14,Población de 35 a 39 años,4.06,30740.68,9321.29,1254.79,462.10,716.58,365.73,...,1.657459,0.883978,8.729282,88.729282,8.127552,3.879059,2.566595,0.622205,1.312464,0.806922
2,28224.0,38.57,Población de 45 a 49 años,6.53,49110.56,14671.80,2491.62,1348.39,940.47,645.40,...,0.458415,0.884086,1.653569,97.003929,3.774709,20.991855,2.577729,0.658091,1.996623,0.089401
4,18003.0,45.22,Población de 35 a 39 años,3.61,31895.02,11766.21,1519.02,405.79,764.29,78.30,...,1.050788,1.401051,7.355517,90.192644,9.769311,1.677735,1.450542,1.555400,0.332052,2.673890
5,8870.0,42.40,Población de 40 a 44 años,4.39,32781.34,10317.77,1332.67,461.16,738.76,370.39,...,0.513820,4.588944,18.993622,75.903614,4.850397,16.775752,5.236092,1.979118,8.080100,1.807698

In [14]:
#data.CODIGO_POSTAL_NUMBER.dropna(axis=0, inplace=True)

In [17]:
data.dropna(inplace=True)

In [19]:
data.CODIGO_POSTAL_NUMBER = data.CODIGO_POSTAL_NUMBER.astype('int')

In [20]:
data.CODIGO_POSTAL

0        8004.0
1       43203.0
2       28224.0
4       18003.0
5        8870.0
         ...
6370    37405.0
6371    26371.0
6372    14811.0
6373     6413.0
6374    15123.0
Name: CODIGO_POSTAL, Length: 6372, dtype: float64

In [22]:
codes_uniques = data.CODIGO_POSTAL_NUMBER.unique()

In [23]:
def get_madrid_codes(df):
    
    df.dropna(inplace=True)
    #df.CODIGO_POSTAL = df.CODIGO_POSTAL.astype('str')
    #df_madrid = df[df.CODIGO_POSTAL.find('28')]
    df_madrid = df[(df.CODIGO_POSTAL>27999) & (df.CODIGO_POSTAL<29000)]
    df_madrid.CODIGO_POSTAL = df.CODIGO_POSTAL.astype('int')
    return df_madrid

In [24]:
df_mad = get_madrid_codes(data)

/home/alejandro.vaca/miniconda/envs/sentinel_env/lib/python3.7/site-packages/pandas/core/generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [25]:
df_mad

,CODIGO_POSTAL_NUMBER,mediaEdad,medianaEdad,nivel_socio_economico,GMTotal,GMVivienda,GMMobiliario,GMEnsenanza,GMElectricidad,GMGasNatural,...,p_viviendas_ruina,p_viviendas_mal_estado,p_viviend_estado_defic,p_viviendas_buen_estado,p_paro_2015,p_turismos,p_vehiculos_comerciales,p_monovolumenes,p_motocicletas,p_todoterrenos
2,28224,38.57,Población de 45 a 49 años,6.53,49110.56,14671.80,2491.62,1348.39,940.47,645.40,...,0.458415,0.884086,1.653569,97.003929,3.774709,20.991855,2.577729,0.658091,1.996623,0.089401
116,28055,32.76,Población de 30 a 34 años,3.97,31123.58,9622.01,1557.04,832.55,604.58,459.85,...,0.833965,2.956785,7.657316,88.551933,6.680121,5.196771,9.162462,16.851665,1.594349,13.511604
174,28220,39.88,Población de 35 a 39 años,6.32,40401.16,13802.55,1784.19,988.16,801.52,568.42,...,0.628437,1.060487,5.891595,92.419482,4.564597,7.776117,2.594756,0.298872,0.230947,0.676539
184,28023,37.45,Población de 45 a 49 años,5.44,45297.02,14308.31,2434.54,1243.78,826.88,623.96,...,0.872748,2.393018,3.688063,93.046171,5.532414,27.175125,0.530947,2.836609,1.569375,1.537108
249,28109,37.19,Población de 40 a 44 años,7.29,53057.48,16263.51,2828.70,1326.32,1023.71,701.17,...,0.309859,0.028169,0.535211,99.126761,4.857543,32.477036,2.096632,7.997301,5.656754,12.564222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5545,28743,47.99,Población de 55 a 59 años,3.22,27731.71,8916.01,1098.22,524.44,748.75,487.00,...,0.499002,0.798403,4.091816,94.610778,6.324111,1132.411067,38.471673,161.791831,35.573123,45.718050
5671,28668,44.78,Población de 70 a 74 años,6.44,53658.18,15344.29,3030.04,1377.06,1146.53,752.25,...,0.000000,0.598802,1.197605,98.203593,4.093567,41.786284,7.283360,1.010101,0.000000,8.559277
5868,28190,47.52,Población de 45 a 49 años,3.68,32016.53,10484.07,1280.50,455.61,813.20,468.55,...,1.688312,1.038961,8.311688,88.961039,4.093567,1101.754386,287.329435,288.888889,28.849903,157.504873
6153,28812,42.04,Población de 35 a 39 años,3.32,30856.50,10133.80,1247.10,568.99,802.70,512.94,...,0.406091,3.350254,12.994924,83.248731,7.434641,71.895425,41.013072,3.594771,12.908497,140.686275
6229,28515,40.98,Población de 35 a 39 años,3.55,35407.09,10647.88,1531.11,676.18,852.44,584.75,...,2.412869,0.536193,6.434316,90.616622,4.733728,8171.301775,306.804734,1039.644970,533.136095,407.988166

In [27]:
df_mad.describe()

,CODIGO_POSTAL_NUMBER,mediaEdad,nivel_socio_economico,GMTotal,GMVivienda,GMMobiliario,GMEnsenanza,GMElectricidad,GMGasNatural,GMSalud,...,p_viviendas_ruina,p_viviendas_mal_estado,p_viviend_estado_defic,p_viviendas_buen_estado,p_paro_2015,p_turismos,p_vehiculos_comerciales,p_monovolumenes,p_motocicletas,p_todoterrenos
count,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,...,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000,266.000000
mean,28502.398496,40.016053,4.158647,33255.651842,11262.539023,1373.195188,649.698759,747.474436,532.799850,919.881805,...,0.950004,1.698287,5.485091,91.866617,7.631457,384.662334,34.254288,47.321944,21.789626,28.699407
std,340.523547,4.016746,0.873363,6649.099810,1777.359733,477.031517,253.552539,110.518000,68.474504,118.689379,...,1.077718,2.062968,5.345307,7.678908,1.926821,1229.943866,84.451426,146.152852,64.665312,96.266459
min,28001.000000,29.940000,2.900000,20370.700000,8096.070000,744.400000,259.940000,562.100000,406.410000,409.720000,...,0.000000,0.000000,0.000000,47.975078,3.507210,0.108513,0.000000,0.060685,0.000000,0.000000
25%,28190.500000,37.285000,3.550000,28484.277500,9921.570000,1050.727500,502.360000,667.125000,486.352500,864.745000,...,0.339871,0.438926,1.799490,89.540892,6.183069,5.181869,1.485421,1.442924,0.671520,0.951007
50%,28535.000000,39.905000,3.930000,30939.035000,10921.605000,1194.595000,578.975000,740.310000,523.505000,894.530000,...,0.699140,1.052550,4.025421,94.123721,7.724291,29.523151,4.459371,5.159237,2.568888,3.953495
75%,28813.750000,42.897500,4.607500,36078.565000,11992.460000,1517.852500,715.190000,808.770000,570.342500,935.637500,...,1.159699,2.047820,7.190610,97.037948,8.898759,173.974999,27.428742,28.473754,17.687332,23.022160
max,28991.000000,49.860000,7.290000,54415.010000,16320.190000,3030.040000,1631.860000,1147.380000,767.810000,1330.050000,...,11.059190,12.616822,38.930294,100.000000,14.446003,12527.272727,950.000000,1686.363636,613.636364,1359.090909

In [29]:
res = nomi.query_postal_code("28007")

In [32]:
res

postal_code         28007
country code           ES
place_name         Madrid
state_name         Madrid
state_code             MD
county_name        Madrid
county_code             M
community_name     Madrid
community_code      28079
latitude          40.4165
longitude         -3.7026
accuracy                4
Name: 0, dtype: object

In [33]:
res['latitude']

40.4165

In [34]:
def get_lon_lat_postal_codes(df):
    nomi = pgeocode.Nominatim('es')
    unique_codes = df.CODIGO_POSTAL.unique()
    dic_ = {'CODIGO_POSTAL': [c for c in unique_codes],
            'lon': [],
            'lat': []}
    for code in dic_['CODIGO_POSTAL']:
        res = nomi.query_postal_code(f"{code}")
        dic_['lon'].append(res['longitude'])
        dic_['lat'].append(res['latitude'])
    
    df_lon_lat = pd.DataFrame(dic_)
    df_lon_lat.CODIGO_POSTAL = df_lon_lat.CODIGO_POSTAL.astype('int')
    df_total = pd.merge(df, df_lon_lat, how='outer', on='CODIGO_POSTAL')
    return df_total

In [35]:
totaldf = get_lon_lat_postal_codes(df_mad)

In [36]:
totaldf

,CODIGO_POSTAL_NUMBER,mediaEdad,medianaEdad,nivel_socio_economico,GMTotal,GMVivienda,GMMobiliario,GMEnsenanza,GMElectricidad,GMGasNatural,...,p_viviend_estado_defic,p_viviendas_buen_estado,p_paro_2015,p_turismos,p_vehiculos_comerciales,p_monovolumenes,p_motocicletas,p_todoterrenos,lon,lat
0,28224,38.57,Población de 45 a 49 años,6.53,49110.56,14671.80,2491.62,1348.39,940.47,645.40,...,1.653569,97.003929,3.774709,20.991855,2.577729,0.658091,1.996623,0.089401,-3.813400,40.4329
1,28055,32.76,Población de 30 a 34 años,3.97,31123.58,9622.01,1557.04,832.55,604.58,459.85,...,7.657316,88.551933,6.680121,5.196771,9.162462,16.851665,1.594349,13.511604,-3.702600,40.4165
2,28220,39.88,Población de 35 a 39 años,6.32,40401.16,13802.55,1784.19,988.16,801.52,568.42,...,5.891595,92.419482,4.564597,7.776117,2.594756,0.298872,0.230947,0.676539,-3.871800,40.4735
3,28023,37.45,Población de 45 a 49 años,5.44,45297.02,14308.31,2434.54,1243.78,826.88,623.96,...,3.688063,93.046171,5.532414,27.175125,0.530947,2.836609,1.569375,1.537108,-3.702600,40.4165
4,28109,37.19,Población de 40 a 44 años,7.29,53057.48,16263.51,2828.70,1326.32,1023.71,701.17,...,0.535211,99.126761,4.857543,32.477036,2.096632,7.997301,5.656754,12.564222,-3.642000,40.5475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,28743,47.99,Población de 55 a 59 años,3.22,27731.71,8916.01,1098.22,524.44,748.75,487.00,...,4.091816,94.610778,6.324111,1132.411067,38.471673,161.791831,35.573123,45.718050,-3.683800,40.9199
262,28668,44.78,Población de 70 a 74 años,6.44,53658.18,15344.29,3030.04,1377.06,1146.53,752.25,...,1.197605,98.203593,4.093567,41.786284,7.283360,1.010101,0.000000,8.559277,-3.878300,40.4050
263,28190,47.52,Población de 45 a 49 años,3.68,32016.53,10484.07,1280.50,455.61,813.20,468.55,...,8.311688,88.961039,4.093567,1101.754386,287.329435,288.888889,28.849903,157.504873,-3.417425,41.1433
264,28812,42.04,Población de 35 a 39 años,3.32,30856.50,10133.80,1247.10,568.99,802.70,512.94,...,12.994924,83.248731,7.434641,71.895425,41.013072,3.594771,12.908497,140.686275,-3.234950,40.4161
265,28515,40.98,Población de 35 a 39 años,3.55,35407.09,10647.88,1531.11,676.18,852.44,584.75,...,6.434316,90.616622,4.733728,8171.301775,306.804734,1039.644970,533.136095,407.988166,-3.216700,40.3667

In [39]:
#totaldf.loc[:, type(totaldf)==object]

In [42]:
#totaldf.dtypes

In [43]:
#totaldf.TIPOLOGIA_LITERAL

In [44]:
totaldf.to_csv('variables_cod_postal_lon_lat.csv', header=True, index=False)

In [ ]:
totaldf.dtypes